steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - file-processing
  - --region=europe-west1
  - --source=.
  - --trigger-bucket=scraped-data-gh
  - --runtime=python311
  - --gen2
  - --trigger-location=europe-west1
  - --service-account=etl-sa@real-estate-analyser-dv.iam.gserviceaccount.com
  - --run-service-account=etl-sa@real-estate-analyser-dv.iam.gserviceaccount.com
  - --entry-point=file_processing
  - --max-instances=1
  - --set-secrets=BOT_API_TOKEN=tbot-api-token:1
  - --set-env-vars=CHAT_ID=${_CHAT_ID}
  - timeout=540s
