steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - file-processing
  - --region=europe-west1
  - --source=.
  - --trigger-bucket=scraped-data-gh
  - --runtime=python311
  - --gen2
  - --entry-point=file_processing
